# Generated by Django 5.0.3 on 2024-04-02 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_pointstransfer_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointstransfer',
            old_name='enter_points_to_transfer',
            new_name='points_to_transfer',
        ),
        migrations.RemoveField(
            model_name='pointstransfer',
            name='enter_destination_username',
        ),
        migrations.RemoveField(
            model_name='pointstransfer',
            name='enter_your_username',
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransfer',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
