# Generated by Django 5.0.3 on 2024-04-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointstransfer',
            old_name='points_to_transfer',
            new_name='money_to_transfer',
        ),
    ]
